services:
  mongodb:
    image: mongo
    container_name: my-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build:
      context: ./backend-nestjs
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    working_dir: /usr/src/app
    volumes:
      - ./backend-nestjs:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - backend-nestjs/.env
    command: npm run start:dev

volumes:
  mongo_data:
