services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: ./backend-nestjs
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    working_dir: /usr/src/app
    volumes:
      - ./backend-nestjs:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev

volumes:
  mongo_data:
