version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command: npm run start:dev

volumes:
  mongo_data:
